apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_image_name
  labels:
    app: docker_image_name
  namespace: default
spec:
  replicas: replica_set
  selector:
    matchLabels:
      app: docker_image_name
  strategy:
    rollingUpdate:
      maxSurge: max_surge
      maxUnavailable: max_unavailable
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker_image_name
    spec:
      containers:
        - image: docker_image_path
          imagePullPolicy: Always
          name: docker_image_name
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: docker_image_name
  labels:
    app: docker_image_name
spec:
  type: LoadBalancer
  selector:
    app: docker_image_name
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
