apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-test:v2.0
  labels:
    app: capstone-test:v2.0
  namespace: default
spec:
  replicas: replica_set
  selector:
    matchLabels:
      app: capstone-test:v2.0
  strategy:
    rollingUpdate:
      maxSurge: max_surge
      maxUnavailable: max_unavailable
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-test:v2.0
    spec:
      containers:
        - image: docker_image_path
          imagePullPolicy: Always
          name: capstone-test:v2.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-test:v2.0
  labels:
    app: capstone-test:v2.0
spec:
  type: LoadBalancer
  selector:
    app: capstone-test:v2.0
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
